const $=s=>document.querySelector(s), days=$("#days"), month=$("#month"), card=$("#calendarCard");
let now=new Date(), view=new Date(now.getFullYear(),now.getMonth(),1), forced="auto";
const pad=n=>String(n).padStart(2,"0");
function sceneFor(h){return h>=5&&h<9?"morning":h>=9&&h<16?"day":h>=16&&h<19?"evening":"night"}
function tick(){const n=new Date(),w=["日","月","火","水","木","金","土"];$("#clock").textContent=`${pad(n.getHours())}:${pad(n.getMinutes())}`;$("#date").textContent=`${n.getFullYear()}年 ${n.getMonth()+1}月 ${n.getDate()}日（${w[n.getDay()]}）`;const p=forced==="auto"?sceneFor(n.getHours()):forced;$("#world").dataset.period=p;$("#greeting").innerHTML=p==="morning"?"Good morning,<br>Have a nice day.":p==="day"?"Good afternoon,<br>Take it easy.":p==="evening"?"Good evening,<br>おつかれさま。":"Good night,<br>ゆっくりすごそう。";$("#speech").textContent=p==="night"?"ねむい... Zzz":p==="evening"?"おつかれさま...":"のんびりいこう";}
function render(){const y=view.getFullYear(),m=view.getMonth(),t=new Date(),first=new Date(y,m,1).getDay(),count=new Date(y,m+1,0).getDate(),pc=new Date(y,m,0).getDate();month.textContent=`${y}.${pad(m+1)}`;days.innerHTML="";for(let i=0;i<42;i++){let d,am=m,out=false;if(i<first){d=pc-first+i+1;am--;out=true}else if(i>=first+count){d=i-first-count+1;am++;out=true}else d=i-first+1;const a=new Date(y,am,d),e=document.createElement("div");e.className="day";e.textContent=d;if(out)e.classList.add("out");else if(a.getDay()===0)e.classList.add("sun");else if(a.getDay()===6)e.classList.add("sat");if(a.toDateString()===t.toDateString())e.classList.add("today");days.appendChild(e)}}
function move(x){view=new Date(view.getFullYear(),view.getMonth()+x,1);render()}
$("#prev").onclick=()=>move(-1);$("#next").onclick=()=>move(1);$("#today").onclick=()=>{let n=new Date();view=new Date(n.getFullYear(),n.getMonth(),1);render()};
let sy=null;card.addEventListener("touchstart",e=>sy=e.touches[0].clientY,{passive:true});card.addEventListener("touchend",e=>{if(sy===null)return;let dy=e.changedTouches[0].clientY-sy;if(Math.abs(dy)>35)move(dy<0?1:-1);sy=null},{passive:true});
document.querySelectorAll("[data-scene]").forEach(b=>b.onclick=()=>{forced=b.dataset.scene;tick()});
tick();render();setInterval(tick,1000);
